import "./globals.css";
import { Oswald } from "next/font/google";
import Header from "@/components/Header";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
