import "./globals.css";
import { Inter, Lora } from "next/font/google";
import Header from "../components/Header";

const lora = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
